export type AdminProductTFunction = (key: string, options?: { defaultValue?: string }) => string;

export const adminProductTranslations: Record<string, string> = {
  'admin.products': 'Products',
  'admin.manageProducts': 'Manage all products',
  'admin.addProduct': 'Add Product',
  'admin.editProduct': 'Edit Product',
  'admin.searchProducts': 'Search products...',
  'admin.active': 'Active',
  'admin.inactive': 'Inactive',
  'admin.edit': 'Edit',
  'admin.delete': 'Delete',
  'admin.cancel': 'Cancel',
  'admin.save': 'Save',
  'admin.back': 'Back',
  'admin.next': 'Next',
  'admin.deleteConfirm': 'Delete this product?',
  'admin.noProducts': 'No products found',
  'admin.activateAllInactive': 'Activate all inactive',
  'admin.statusFilterAll': 'All statuses',
  'admin.statusFilterActive': 'Active only',
  'admin.statusFilterInactive': 'Inactive only',
  'admin.totalProducts': 'Total',
  'admin.form.title': 'Title',
  'admin.form.category': 'Category',
  'admin.form.status': 'Status',
  'admin.form.originalPrice': 'Original Price',
  'admin.form.currentPrice': 'Current Price',
  'admin.form.discount': 'Discount',
  'admin.form.description': 'Description',
  'admin.form.freeDelivery': 'Free Delivery',
  'admin.form.freeDeliveryDesc': 'Enable free delivery for this product',
  'admin.form.clothesOptions': 'Clothes options',
  'admin.form.clothesGender': 'For',
  'admin.form.clothesMen': 'Men',
  'admin.form.clothesWomen': 'Women',
  'admin.form.clothesStitch': 'Stitch type',
  'admin.form.clothesStitched': 'Stitched',
  'admin.form.clothesUnstitched': 'Unstitched',
  'admin.form.clothesSizes': 'Available sizes',
  'admin.form.clothesSizesHint': 'Select all sizes you sell for this item',
  'admin.form.clothesSizesHintStitched': 'Required — select all sizes you sell for this stitched item',
  'admin.form.clothesSizesHintUnstitched': 'Optional — add sizes if customers may choose one when ordering',
  'admin.form.optional': '(optional)',
  'admin.form.featuresOptional': 'Add product features (optional). You can skip this step.',
  'admin.form.mainImage': 'Main Image',
  'admin.form.additionalImages': 'Additional Images',
  'admin.form.productImages': 'Product images',
  'admin.form.productImagesDesc':
    'First image is the main photo on the shop. Each upload is cropped before saving. Up to 12 images.',
  'admin.form.imagesAdded': 'images',
  'admin.form.noImagesYet': 'No images yet. Upload or paste a URL below.',
  'admin.form.addImages': 'Upload images (crop before save)',
  'admin.form.addUrl': 'Add URL',
  'admin.form.replaceImage': 'Replace',
  'admin.form.setAsMain': 'Set main',
  'admin.form.imagesLimitReached': 'Maximum 12 images reached. Remove one to add more.',
  'admin.form.uploading': 'Uploading…',
  'admin.form.imageUrlPlaceholder': 'Enter image URL...',
  'admin.form.preview': 'Preview',
  'admin.form.step': 'Step',
  'admin.form.of': 'of',
  'admin.form.tab.basic': 'Basic Info',
  'admin.form.tab.features': 'Features',
  'admin.form.tab.images': 'Images',
  'admin.form.errors.mainImageRequired': 'Main image URL is required',
  'admin.form.pricingTiers': 'Quantity Pricing',
  'admin.form.pricingTiersDesc': 'Set different prices for different quantities',
  'admin.form.noPricingTiers': 'No quantity pricing set - Click "Add Tier" to add',
  'admin.form.shortDescription': 'Short summary',
  'admin.form.shortDescriptionHint': 'Shop listing cards only — not shown on product page (leave empty if unsure)',
  'admin.form.sku': 'SKU / Product code',
  'admin.form.skuHint': 'Shown on product page as “Product code”',
  'admin.form.brand': 'Brand',
  'admin.form.brandHint': 'Shown in Product details on the product page',
  'admin.form.stock': 'Stock quantity',
  'admin.form.stockHint': 'Shown at top as “Total stock” and in Product details (0 = out of stock)',
  'admin.form.tags': 'Tags',
  'admin.form.tagsHint': 'Shown as tags in Product details (comma-separated)',
  'admin.form.fabric': 'Fabric / material',
  'admin.form.fabricHint': 'Clothes only — shown in Product details',
  'admin.form.costPrice': 'Cost price (PKR)',
  'admin.form.costPriceHint': 'Never shown to customers — for your profit records only',
  'admin.form.seoTitle': 'SEO title',
  'admin.form.seoTitleHint': 'Google & Facebook link preview only — not on product page',
  'admin.form.seoDescription': 'SEO description',
  'admin.form.seoDescriptionHint': 'Search engines only — not on product page',
  'admin.form.catalogSectionDesc':
    'Optional fields below. Each label shows where it appears: shop, product page, or admin only.',
  'admin.form.seoSectionDesc':
    'For Google and social sharing only. Customers do not see these on the product page.',
  'admin.form.startWithCategory': 'Step 1 — Choose category first',
  'admin.form.startWithCategoryDesc':
    'Category controls which extra fields appear (sizes, colors, Men/Women for clothes & watches, etc.).',
  'admin.form.categoryAudience': 'Audience',
  'admin.form.clothesGenderHint': 'Shown on product page (top right near price).',
  'admin.form.clothesStitchHint': 'Stitched items require at least one size.',
  'admin.form.clothesColors': 'Available colors',
  'admin.form.clothesColorsHint': 'Optional — shown in product details when selected.',
  'categories.all': 'All',
  'categories.cosmetics': 'Cosmetics',
  'categories.jewelry': 'Jewelry',
  'categories.watches': 'Watches',
  'categories.makeup': 'Makeup',
  'categories.clothes': 'Clothes',
  'categories.shoes': 'Shoes',
  'categories.electronics': 'Electronics',
  'categories.general': 'General',
  'categories.bags': 'Bags',
  'categories.menfashion': 'Men Fashion',
  'categories.ladiesbag': 'Jewelry',
  'categories.wallets': 'Watches',
  'categories.lace': 'Clothes',
};

export const adminProductT: AdminProductTFunction = (key, options) =>
  adminProductTranslations[key] || options?.defaultValue || key;

export function isValidProductImageUrl(url: string): boolean {
  if (!url || !url.trim()) return false;
  if (url.startsWith('/')) return true;
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}
